"""English USMLE Step 1 syllabus used by the default MAID question tree."""

USMLE_STEP1_SYLLABUS = {
    "USMLE Step 1": {
        "Foundational Science": {
            "Cell Biology and Pathology": [
                "Cell injury, adaptation, and death",
                "Inflammation and tissue repair",
                "Neoplasia and carcinogenesis",
                "Cell signaling and signal transduction",
                "Cell cycle regulation",
                "Cellular organelles and intracellular trafficking",
                "Extracellular matrix and cell adhesion",
                "Stem cells and cellular differentiation",
                "Oxidative stress and free radical injury",
                "Protein folding and degradation",
            ],
            "Biochemistry and Molecular Biology": [
                "Enzyme kinetics and regulation",
                "Carbohydrate metabolism",
                "Lipid metabolism",
                "Amino acid metabolism",
                "Nucleotide metabolism",
                "Vitamins and nutritional deficiencies",
                "DNA replication and repair",
                "Transcription and RNA processing",
                "Translation and protein synthesis",
                "Molecular laboratory techniques",
            ],
            "Genetics": [
                "Mendelian inheritance",
                "Non-Mendelian inheritance",
                "Chromosomal abnormalities",
                "Population genetics and Hardy-Weinberg equilibrium",
                "Genetic testing and pedigree analysis",
                "Genomic imprinting and uniparental disomy",
                "Trinucleotide repeat disorders",
                "Mitochondrial inheritance",
                "Multifactorial inheritance",
                "Gene therapy and genetic counseling",
            ],
            "Immunology": [
                "Innate immune responses",
                "Adaptive immune responses",
                "Antigen presentation and major histocompatibility complex",
                "B-cell development and antibody function",
                "T-cell development and function",
                "Complement pathways",
                "Hypersensitivity reactions",
                "Primary and secondary immunodeficiencies",
                "Autoimmune disease mechanisms",
                "Transplantation immunology",
                "Vaccines and immunization principles",
            ],
            "Microbiology": [
                "Bacterial structure, genetics, and virulence",
                "Gram-positive bacterial infections",
                "Gram-negative bacterial infections",
                "Mycobacterial and spirochetal infections",
                "DNA virus infections",
                "RNA virus infections",
                "Fungal infections",
                "Protozoal infections",
                "Helminth infections",
                "Prion diseases",
                "Antimicrobial pharmacology",
                "Healthcare-associated infection prevention",
            ],
            "General Pharmacology": [
                "Pharmacokinetics",
                "Pharmacodynamics",
                "Drug metabolism and elimination",
                "Receptor signaling and dose-response relationships",
                "Drug interactions",
                "Adverse drug reactions",
                "Autonomic pharmacology",
                "Drug development and clinical trials",
                "Toxicology and antidotes",
                "Principles of prescription safety",
            ],
        },
        "Organ Systems": {
            "Cardiovascular System": [
                "Cardiac embryology and anatomy",
                "Cardiac electrophysiology",
                "Cardiac cycle and pressure-volume loops",
                "Hemodynamics and vascular physiology",
                "Congenital heart disease",
                "Ischemic heart disease",
                "Heart failure",
                "Valvular heart disease",
                "Cardiomyopathies and myocarditis",
                "Arrhythmias and conduction disorders",
                "Hypertension and vascular disease",
                "Cardiovascular pharmacology",
            ],
            "Respiratory System": [
                "Respiratory anatomy and embryology",
                "Pulmonary mechanics and compliance",
                "Ventilation-perfusion relationships",
                "Gas exchange and oxygen transport",
                "Acid-base respiratory physiology",
                "Obstructive lung disease",
                "Restrictive lung disease",
                "Pulmonary vascular disease",
                "Respiratory infections",
                "Lung neoplasms",
                "Pleural disease",
                "Respiratory pharmacology",
            ],
            "Renal and Urinary System": [
                "Renal anatomy and embryology",
                "Glomerular filtration and renal blood flow",
                "Tubular transport",
                "Water balance and urine concentration",
                "Electrolyte disorders",
                "Acid-base disorders",
                "Glomerular diseases",
                "Tubulointerstitial diseases",
                "Acute kidney injury",
                "Chronic kidney disease",
                "Urinary tract obstruction and stones",
                "Renal pharmacology",
            ],
            "Gastrointestinal System": [
                "Gastrointestinal embryology and anatomy",
                "Gastrointestinal motility and secretion",
                "Digestion and nutrient absorption",
                "Esophageal disorders",
                "Gastric and duodenal disorders",
                "Inflammatory bowel disease",
                "Malabsorption syndromes",
                "Gastrointestinal infections",
                "Gastrointestinal neoplasms",
                "Liver disease",
                "Biliary and pancreatic disease",
                "Gastrointestinal pharmacology",
            ],
            "Endocrine System": [
                "Hormone synthesis and signaling",
                "Hypothalamic and pituitary disorders",
                "Thyroid physiology and disease",
                "Parathyroid and calcium disorders",
                "Adrenal physiology and disease",
                "Diabetes mellitus",
                "Hypoglycemic disorders",
                "Multiple endocrine neoplasia",
                "Endocrine tumors",
                "Endocrine pharmacology",
            ],
            "Reproductive System": [
                "Sexual differentiation and reproductive embryology",
                "Male reproductive physiology and pathology",
                "Female reproductive physiology and pathology",
                "Menstrual cycle regulation",
                "Pregnancy physiology",
                "Placental pathology",
                "Infertility",
                "Sexually transmitted infections",
                "Breast disease",
                "Reproductive neoplasms",
                "Reproductive pharmacology and contraception",
            ],
            "Hematology and Oncology": [
                "Hematopoiesis",
                "Red blood cell physiology",
                "Microcytic and macrocytic anemia",
                "Hemolytic anemia",
                "White blood cell disorders",
                "Leukemia and lymphoma",
                "Platelet disorders",
                "Coagulation disorders",
                "Transfusion medicine",
                "Antineoplastic pharmacology",
                "Oncogenes and tumor suppressor genes",
            ],
            "Musculoskeletal, Skin, and Connective Tissue": [
                "Bone and cartilage physiology",
                "Skeletal muscle physiology",
                "Bone and joint disorders",
                "Inflammatory arthritis",
                "Connective tissue diseases",
                "Muscular dystrophies and myopathies",
                "Peripheral nerve and neuromuscular junction disorders",
                "Skin structure and function",
                "Inflammatory skin disease",
                "Skin infections and neoplasms",
                "Musculoskeletal pharmacology",
            ],
            "Nervous System and Special Senses": [
                "Neuroembryology and neuroanatomy",
                "Neuronal signaling and neurotransmitters",
                "Motor and sensory pathways",
                "Cerebrovascular disease",
                "Seizure disorders",
                "Neurodegenerative disease",
                "Demyelinating disease",
                "Central nervous system infections",
                "Brain and spinal cord tumors",
                "Vision and ocular disease",
                "Hearing and vestibular disease",
                "Neurologic pharmacology",
            ],
            "Behavioral Health": [
                "Human development across the lifespan",
                "Learning, conditioning, and memory",
                "Sleep physiology and disorders",
                "Psychotic disorders",
                "Mood disorders",
                "Anxiety and trauma-related disorders",
                "Personality disorders",
                "Substance use disorders",
                "Eating disorders",
                "Psychiatric pharmacology",
            ],
            "Multisystem Processes": [
                "Shock and hemodynamic collapse",
                "Sepsis and systemic inflammatory response",
                "Fever and thermoregulation",
                "Fluid and electrolyte management",
                "Nutritional assessment and deficiencies",
                "Aging physiology",
                "Amyloidosis",
                "Sarcoidosis",
                "Environmental and occupational disease",
                "Multisystem genetic syndromes",
            ],
        },
        "Biostatistics, Epidemiology, and Ethics": {
            "Biostatistics and Epidemiology": [
                "Study designs",
                "Bias, confounding, and effect modification",
                "Sensitivity, specificity, and predictive values",
                "Likelihood ratios and diagnostic testing",
                "Relative risk, odds ratio, and attributable risk",
                "Confidence intervals and hypothesis testing",
                "Common probability distributions",
                "Survival analysis",
                "Systematic reviews and meta-analysis",
                "Screening and disease prevention",
            ],
            "Communication and Ethics": [
                "Informed consent and decision-making capacity",
                "Confidentiality and mandatory reporting",
                "Advance directives and surrogate decision making",
                "End-of-life care",
                "Medical error disclosure",
                "Professional boundaries and conflicts of interest",
                "Patient-centered communication",
                "Working with interpreters",
                "Child and adolescent consent",
                "Research ethics",
                "Organ donation and transplantation ethics",
                "Resource allocation and public health ethics",
            ],
        },
    }
}
